# site settings
title: Fabian
subtitle: Volkers
email: contact@fabianvolkers.com
description: Software Engineer, Event Technician and 3D Printing Enthusiast
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ffvo.dev # the base hostname & protocol for your site
author: Fabian Volkers
street_address:
city:
state:
zip_code:
country:
phone:

permalink: /:title
page_excerpts: true
collections:
  projects:
    output: true


# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/FabianVolkers
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/fabianvolkers
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
# Disabled during construction
- all_posts.md
- elements.md
- events.md
- projects.md
- generic.md
- landing.md
- gardena-valve-servo-adapter.md
